MERGE(a:Context {name:'book'})
MERGE(b:Context {name:'by'})
MERGE(c:Context {name:'Ursula K. LeGuinn'})
MERGE(d:Book {name:'AWoE'})
MERGE (a)-[_1:SUB]->(b)
MERGE (b)-[_2:SUB]->(c)
MERGE (c)-[_3:CTX]->(d)

MERGE(a:Context {name:'book'})
MERGE(b:Context {name:'by'})
MERGE(c:Context {name:'Roger Clark'})
MERGE(d:Book {name:'Illuminatus II!'})
MERGE (a)-[_1:SUB]->(b)
MERGE (b)-[_2:SUB]->(c)
MERGE (c)-[_3:CTX]->(d)
