services:
  web:
    build:
      context: .
      args:
        - PUBLIC_APPKIT_PROJECT_ID=${PUBLIC_APPKIT_PROJECT_ID}
    ports:
      - 42069:3000
    env_file:
      - .env.docker
    volumes:
      - .:/app
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:community
    container_name: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    env_file:
      - .env.docker
    environment:
      - NEO4J_PLUGINS=["apoc-extended"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: [
        "CMD",
        "cypher-shell",
        "-u", "${PUBLIC_NEO4J_USER:-neo4j}",
        "-p", "${PUBLIC_NEO4J_PASS:-Password from within Docker.}",
        "RETURN 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
  neo4j_logs:
