// Generated by Google's Gemini

import gremlin from 'gremlin'
import { map2Obj } from '$lib'

const { DriverRemoteConnection } = gremlin.driver
const {
  t: T,
  statics: __,
  AnonymousTraversalSource: { traversal },
} = gremlin.process

function formatCSVField(rawValue: unknown) {
  if(rawValue == null) return ''

  let stringValue = (
    Array.isArray(rawValue)
    ? rawValue.join('|')
    : String(rawValue)
  )

  if (/[,"\n]/.test(stringValue)) {
    stringValue = `"${stringValue.replace(/"/g, '""')}"`
  }
  return stringValue
}

// Determined by Cytoscape's input format
export async function graphToCSV() {
  const url = 'ws://localhost:8182/gremlin'
  const dc = new DriverRemoteConnection(url)
  const g = traversal().withRemote(dc)

  try {
    const fileHandle = await (window as any).showSaveFilePicker({
      suggestedName: `mïmis_export.${new Date().toISOString()}.csv`,
      types: [{
        description: 'CSV File',
        accept: { 'text/csv': ['.csv'] },
      }],
    })

    const stream = await fileHandle.createWritable()

    const [vKeys, eKeys] = await Promise.all([
      g.V().properties().key().dedup().toList(),
      g.E().properties().key().dedup().toList(),
    ])
    const allDynamicKeys = Array.from(new Set([...vKeys, ...eKeys]))
    const nonpropHeaders = [
      'id', 'outV', 'inV', 'inLabel', 'outLabel', 'label',
    ] as const
    const headers = [...nonpropHeaders, ...allDynamicKeys]

    stream.write(headers.join(',') + '\n')

    // const projection = ['type', ...nonpropHeaders, 'props']
    const edges = await (
      // g.E().project(...projection)
      g.E().project(
        'id', 'outV', 'inV', 'inLabel', 'outLabel', 'label',
        'inProps', 'outProps', 'props'
      )
      .by(T.id)
      .by(__.outV().id())
      .by(__.inV().id())
      .by(__.inV().label())
      .by(__.outV().label())
      .by(T.label)
      .by(__.valueMap())
      .by(__.outV().valueMap())
      .by(__.inV().valueMap())
      .toList()
    )

    for(const edgeMap of edges) {
      const edge = map2Obj(edgeMap)
      const { props, inProps, outProps } = edge
      const properties = {
        ...props,
        ...inProps,
        ...outProps,
      }

      const fields = {
        'id': edge.id?.relationId ?? edge.id,
        'outV': edge.outV,
        'inV': edge.inV,
        'inLabel': edge.inLabel,
        'outLabel': edge.outLabel,
        'label': edge.label,
      } as const

      const row = headers.map((header) => {
        if(header === 'type') return 'edge'

        if(fields.hasOwnProperty(header)) {
          return formatCSVField(fields[header]);
        }

        const val = properties[header]
        console.debug({ header, properties, val })
        if(val) {
          return formatCSVField(
            Array.isArray(val) ? val[0] : val
          )
        }

        return null;
      });

      await stream.write(`${row.join(',')}\n`);
    }

    await stream.close()
  } catch (error) {
      console.error({ 'Error During Export': error })
  } finally {
      await dc.close()
  }
}
