// Generated by Google's Gemini

import gremlin from 'gremlin'

const { DriverRemoteConnection } = gremlin.driver
const {
  withOptions,
  t,
  EnumValue,
  statics: __,
  AnonymousTraversalSource: { traversal },
} = gremlin.process

function formatCSVField(rawValue: unknown) {
  if(rawValue == null) return ''

  let stringValue = (
    Array.isArray(rawValue)
    ? rawValue.join('|')
    : String(rawValue)
  )

  if (/[,"\n]/.test(stringValue)) {
    stringValue = `"${stringValue.replace(/"/g, '""')}"`
  }
  return stringValue
}

// Determined by Cytoscape's input format
export async function graphToCSV() {
  const url = 'ws://localhost:8182/gremlin'
  const dc = new DriverRemoteConnection(url)
  const g = traversal().withRemote(dc)

  try {
      const fileHandle = await (window as any).showSaveFilePicker({
        suggestedName: `mïmis_export.${new Date().toISOString()}.csv`,
        types: [{
          description: 'CSV File',
          accept: { 'text/csv': ['.csv'] },
        }],
      })

      const stream = await fileHandle.createWritable()

      const [vKeys, eKeys] = await Promise.all([
        g.V().properties().key().dedup().toList(),
        g.E().properties().key().dedup().toList(),
      ])

      const allDynamicKeys = Array.from(new Set([...vKeys, ...eKeys]))

      const headers = [
        'type', 'id', 'inV label', 'edge label', 'outV', 'inV',
        ...allDynamicKeys,
      ]

      stream.write(headers.join(',') + '\n')

      const vertices = await (
        g.V().valueMap().with_(withOptions.tokens).toList()
      )

      for(const vertex of vertices) {
        const vMap = vertex as Map<
          string, InstanceType<typeof EnumValue> | string | number
        >

        const row = headers.map((header) => {
          switch(header) {
            case 'type': return 'node'
            case 'id': return vMap.get(t.id as string)
            case 'edge label': return ''
            case 'inV label': return vMap.get(t.label as string)
            case 'inV': return ''
            case 'outV': return vMap.get(t.id as string)
            default: return vMap.get(header)
          }
        }).map(formatCSVField)

        stream.write(`${row.join(',')}\n`)
      }

      const edges = await (
        g.E().project('id', 'label', 'outV', 'inV', 'props')
        .by(t.id)
        .by(t.label)
        .by(__.outV().id())
        .by(__.inV().id())
        .by(__.valueMap())
        .toList()
      )

      for(const edge of edges) {
        const eMap = edge as Map<string, any>
        const propsMap = eMap.get('props') as Map<string, any>

        console.debug({ eMap, propsMap })

        const row = headers.map((header) => {
          if(header === 'type') return 'edge'

          if(['id', 'inV label', 'edge label', 'outV', 'inV'].includes(header)) {
            let val = eMap.get(header)
            switch(header) {
              case 'id': {
                val = val.relationId
                break
              }
              case 'edge label': {
                val = eMap.get('label' as string)
                break
              }
            }
            return formatCSVField(val)
          }

          return propsMap ? formatCSVField(propsMap.get(header)) : ''
        })
        stream.write(`${row.join(',')}\n`)
      }

      await stream.close()
  } catch (error) {
      console.error('Error during export:', error)
  } finally {
      await dc.close()
  }
}
